### PR TITLE
Updated REQ-ID 023 - to generic reports

### PR DESCRIPTION
**Pull request by radvansky-tomas**
REQ-ID 023 Contained specific daily reports, which might seem constraining in the future development. I suggest to create generic reporting module, which will allow users with proper permissions to create generic reports based on their preferences. For example they should be able to specify date (from - to), field what they want to report (username, last login, type of user, etc...)

### CODE REVIEW

**Comment by vapourer** [comment]
Personally, I still find this requirement too vague.  Without more information about the nature of the report, I would struggle to come up with an associated non-functional requirement.  For example, different response times might be anticipated according to content.  Also, some reports could have confidentiality implications which don't exist in others.  And the interviews mention automatic reports (daily and weekly) vs ad hoc reports.  So which automated reports would be daily, which weekly?  Trying to pre-empt by providing fields could well be a solution in the end, but I think that even doing that relies on a lot of assumptions.
Really, I think we needed to go back to the interviewees (Sebastian's ask the interviewee thread) to clarify, but my suggestion would be that there isn't time for that now.  Indeed I would suggest removing this requirement because of its vagueness, even though in the real world we would certainly need to consider reporting.
Once again, I will go with the flow on this, but 23 is one requirement I don't wish to end up with to try and attempt the TMA question.

**Comment by radvansky-tomas** [comment]
I think that reports are always vague in terms of requirements. If you think about reports in general, its more less presentation of data in the way of user wants. Even though interviewers mentioned some information as you mentioned - daily/weakly/automatic/adhoc etc.. they really don't know (in detail) what exactly they will need. BUT certainly they believe that this "tool" should help them understand raw data. 

This is why, I removed any constrains from requirement and suggested to prepare generic module for products, which should allow to take some generic queries where users will be able to specify what they want to see in report.

Example:
Select ALL users, who are members, FROM last year AND gender=female AND payment_type = credit SORT-BY DoB

I personally think that we can create many NFRs for this requirement, exactly because of its  vagueness

**Comment by vapourer** [comment]
Well, I don't think this is passing the quality gate on a number of counts.  I wouldn't have a clue what to develop from this requirement as it stands.  Your suggestions are not unreasonable, but include assumptions and solution implications eg that there is a SQL database and that there will be a UI that can receive SQL input.
But it is not these requirements that we need to be assessing to that degree for the assignment :-).  I don't wish to use this one, but if you or somebody else does, it's fine by me :-).

**Comment by radvansky-tomas** [comment]
Sure you are right in terms of information, but this is the case for every other u choose. Text what we have is very short to define requirements in details.

Even tasks like taking credit card payments can be divided into 50 different tasks, if we have to develop it from scratch , on the other hand you use payment gate, you will have tasks regarding integration etc.

But yes, reporting module will include multiple dependancies which are currently not a part of requirements, as you mentioned DB, UI etc. On the other hand, if this is real product, You need to create "EPIC" tasks such as Generic Reporting, and then as development goes add more and more subtasks and evolve. 

I know that currently we dont have enough information, but this is the case for almost every other requirement...

**Comment by vapourer** [comment]
But many of the other requirements are atomic enough to qualify for the level expected at this stage.  To my eye, this one isn't and relies too much on assumptions, but my strongest feeling is that we need to complete this exercise as soon as possible, so that we are all comfortable that we can tackle question 2.  If you can make use of this in its current form, than why not? :-)

**Comment by radvansky-tomas** [comment]
I've already pushed one NFRs for this requirement, so you can checked what I had in mind

**Comment by vapourer** [comment]
Hi Tomas
May I clarify that you mean that you have decided that you wish to use functional requirement 23 for your TMA, and that you have already posted your associated non-functional requirement to Master (I haven't looked at that yet)?  If so, may I suggest you post your choice of functional requirement on the forum (the TMA question asks for that)?  If you don't mind doing so, I will certainly merge this for you, if nobody else does in the meantime.

**Comment by radvansky-tomas** [comment]
Yes I did;) right after my commit

**Pull request merged**
